// These constants are used throughout the application for various configurations and limits.

export const API_CONSTANTS = {
  MAX_PAGE_SIZE: 100,
  DEFAULT_PAGE_SIZE: 20,
  MAX_EXPORT_RECORDS: 10000,
  LOG_RETENTION_YEARS: 7,
  LOG_RETENTION_DAYS: 7 * 365,
  BACKUP_RETENTION_DAYS: 30,
  BACKUP_SCHEDULE: "0 2 * * *",
  DEFAULT_SESSION_TIMEOUT: 30 * 60 * 1000,
  MAX_SESSION_TIMEOUT: 8 * 60 * 60 * 1000,
} as const;

export const VALIDATION_CONSTANTS = {
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_METADATA_SIZE: 10000,
} as const;
