export const AUDIT_CONSTANTS = {
  LOG_RETENTION_YEARS: 7,
  LOG_RETENTION_DAYS: 7 * 365,

  BACKUP_RETENTION_DAYS: 30,
  BACKUP_SCHEDULE: "0 2 * * *",

  DEFAULT_SESSION_TIMEOUT: 30 * 60 * 1000,
  MAX_SESSION_TIMEOUT: 8 * 60 * 60 * 1000,

  EVENT_TYPES: {
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_CREATED: "USER_CREATED",
    USER_UPDATED: "USER_UPDATED",
    USER_DEACTIVATED: "USER_DEACTIVATED",
    PATIENT_CREATED: "PATIENT_CREATED",
    PATIENT_UPDATED: "PATIENT_UPDATED",
    PATIENT_ACCESSED: "PATIENT_ACCESSED",
    EHR_CREATED: "EHR_CREATED",
    EHR_UPDATED: "EHR_UPDATED",
    EHR_ACCESSED: "EHR_ACCESSED",
    DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
    DOCUMENT_ACCESSED: "DOCUMENT_ACCESSED",
    APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
    APPOINTMENT_UPDATED: "APPOINTMENT_UPDATED",
    APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
    PRESCRIPTION_CREATED: "PRESCRIPTION_CREATED",
    PRESCRIPTION_UPDATED: "PRESCRIPTION_UPDATED",
    ORDER_PLACED: "ORDER_PLACED",
    WORKFLOW_STEP_COMPLETED: "WORKFLOW_STEP_COMPLETED",
    INVENTORY_UPDATED: "INVENTORY_UPDATED",
    INVOICE_CREATED: "INVOICE_CREATED",
    BACKUP_CREATED: "BACKUP_CREATED",
    BACKUP_RESTORED: "BACKUP_RESTORED",
    POLICY_UPDATED: "POLICY_UPDATED",
    MAINTENANCE_SCHEDULED: "MAINTENANCE_SCHEDULED",
    SYSTEM_ERROR: "SYSTEM_ERROR",
    SECURITY_VIOLATION: "SECURITY_VIOLATION",
  },

  RISK_LEVELS: {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
    CRITICAL: "CRITICAL",
  },

  USER_ROLES: {
    ADMIN: "ADMIN",
    DOCTOR: "DOCTOR",
    NURSE: "NURSE",
    PATIENT: "PATIENT",
    SYSTEM: "SYSTEM",
  },
};

export const API_CONSTANTS = {
  MAX_PAGE_SIZE: 100,
  DEFAULT_PAGE_SIZE: 20,
  MAX_EXPORT_RECORDS: 10000,
} as const;

export const VALIDATION_CONSTANTS = {
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_METADATA_SIZE: 10000,
} as const;
